services:
  # ==========================
  # Database Mongo
  # ==========================
  mongo:
    image: mongo:4.4
    container_name: revolusi-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"   # optional, hapus kalau cukup internal
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ==========================
  # Backend Node.js
  # ==========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: revolusi-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3001:3001"

  # ==========================
  # Frontend React (Nginx serve langsung)
  # ==========================
  frontend:
    build:
      context: ./fe-wablash
      dockerfile: Dockerfile
    container_name: revolusi-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

# ==========================
# Volumes
# ==========================
volumes:
  mongo_data:
